#!/usr/bin/env bash
set -e

# yarn global add inliner, requires NodeJS & yarn installed
# --nosvg => otherwise will strip HTML IDs off of SVG elements
inliner --nosvg index.html > dist/index.html
# -a => archive mode, i.e. copy recursuvely and preserve permissions etc.
# --del => if we delete a file from the source, also delete it from the destination, so we clean up old files
# --ignore-missing-args => if one of the source directories is missing, just skip it
# Listing the source directories without a slash is intentional.
# It tells rsync to create e.g. dist/music and put the contents of music into dist/music.
rsync -a --del --ignore-missing-args music dist
# yarn global add sw-precache, requires NodeJS & yarn installed
# --root => use the built version of the site
# --maximumFileSizeToCacheInBytes => otherwise will skip audio files, size here is 20MB
sw-precache --root=dist --maximumFileSizeToCacheInBytes=20971520

size="$(wc -c <"dist/index.html")"
echo "index.html size: $(echo "scale=1; $size/1024" | bc)KB"