source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.1'

# Core Rails with native dependencies
#versions for bcrypt bootsnap ffi msgpack nio4r nokogiri pg puma sassc websocket-driver need to match base-image/Dockerfile exactly.
gem 'bcrypt', '3.1.12'
gem 'ffi', '1.10.0'
gem 'msgpack', '1.2.7'
gem 'nio4r', '2.3.1'
gem 'nokogiri', '1.10.1'
gem 'sassc', '2.0.1'
gem 'websocket-driver', '0.7.0'

# Core Rails
gem 'rails', '~> 5.2.2'
gem 'pg', '1.1.4'
gem 'puma', '4.3.12'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '1.4.1', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'annotate'
end
